'use strict';
const $=id=>document.getElementById(id),money=n=>Number(n).toLocaleString('ru-RU',{style:'currency',currency:'RUB'}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='soffitto-mobile-outbox-v1';let data={dealers:[],ops:[]},selected=null,flushing=false,loggedIn=false;
let queue=[];try{queue=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(queue))throw Error();}catch{$('status').textContent='Не удалось прочитать очередь. Не очищайте данные браузера.';}
function persist(next){localStorage.setItem(KEY,JSON.stringify(next));queue=next;drawQueue();}
async function api(path,body){const r=await fetch('/mobile/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const value=await r.json();if(!r.ok){if(r.status===401){loggedIn=false;$('login').hidden=false;$('cabinet').hidden=true;}throw Error(value.message||'Не удалось выполнить запрос');}return value;}
const status=text=>{$('status').textContent=text;};
function drawQueue(){$('pending').hidden=!queue.length;$('queue').innerHTML=queue.map(x=>'<div class="row"><b>'+esc(x.kind==='payment'?'Оплата · '+money(x.amount):'Новый дилер · '+x.name)+'</b><p>Ожидает отправки. В общей базе ещё не подтверждено.</p></div>').join('');}
function draw(){const q=$('search').value.toLocaleLowerCase('ru');const digits=q.replace(/\D/g,'');const ds=data.dealers.filter(d=>d.name.toLocaleLowerCase('ru').includes(q)||(digits&&String(d.phone).replace(/\D/g,'').includes(digits)));$('dealers').innerHTML=ds.length?ds.map(d=>'<article class="row"><h3>'+esc(d.name)+'</h3><p>'+esc(d.phone)+' · '+esc(d.city||'Город не указан')+'</p><div class="amount">'+(d.debt<0?'Аванс: ':'Долг: ')+money(Math.abs(d.debt))+'</div><button data-pay="'+esc(d.id)+'">Внести оплату</button><button class="secondary" data-history="'+esc(d.id)+'">История дилера</button></article>').join(''):'<p>Дилеры не найдены</p>';const today=new Date().toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'});$('today').textContent=money(data.ops.filter(o=>o.type==='payment'&&new Date(o.ts).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})===today).reduce((a,o)=>a+Number(o.total),0));drawQueue();}
function history(id){$('dealersView').hidden=true;$('historyView').hidden=false;const rows=data.ops.filter(o=>id==null||String(o.dealerId)===String(id)).sort((a,b)=>(b.ts||0)-(a.ts||0));$('history').innerHTML=rows.map(o=>'<article class="row"><h3>'+esc(o.dealer)+'</h3><b>'+esc({payment:'Оплата',sale:'Продажа',initial_debt:'Начальный долг'}[o.type]||'Операция')+' · '+money(o.total)+'</b><p>'+esc(o.date)+' · '+esc(o.method||'')+'</p><p>'+esc(o.note||'')+'</p></article>').join('')||'<p>Операций пока нет</p>';}
async function refresh(){try{data=await api('summary');loggedIn=true;$('login').hidden=true;$('cabinet').hidden=false;draw();status('Данные общей базы обновлены');return true;}catch(e){status(e.message);return false;}}
async function flush(){if(flushing||!loggedIn)return;flushing=true;try{while(queue.length){await api('commands',queue[0]);persist(queue.slice(1));status('Сохранено в общей базе');}await refresh();}catch(e){status(e.message+' Запись остаётся в очереди.');}finally{flushing=false;}}
function enqueue(item){persist([...queue,{...item,requestId:crypto.randomUUID()}]);status('Запись сохранена на телефоне и ожидает отправки');void flush();}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('login',{password:new FormData(e.target).get('password')});e.target.reset();if(await refresh())await flush();}catch(e){status(e.message);}finally{button.disabled=false;}};
$('dealers').onclick=e=>{const pay=e.target.closest('[data-pay]'),h=e.target.closest('[data-history]');if(h)return history(h.dataset.history);if(!pay)return;selected=data.dealers.find(d=>String(d.id)===pay.dataset.pay);$('recipient').textContent=selected.name+' · долг '+money(selected.debt);$('paymentForm').reset();$('payment').showModal();};
$('paymentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),amount=Number(String(f.get('amount')).replace(/\s/g,'').replace(',','.'));if(!Number.isFinite(amount)||amount<=0||amount>1e9||Math.abs(amount*100-Math.round(amount*100))>0.00001)return alert('Укажите корректную сумму до копеек');if(amount>Math.max(0,selected.debt)&&!confirm('Оплата превышает долг. Разница будет авансом. Сохранить?'))return;try{enqueue({kind:'payment',dealerId:selected.id,amount,method:f.get('method'),note:f.get('note'),ts:Date.now()});$('payment').close();}catch(e){alert('Не удалось сохранить на телефоне: '+e.message);}};
$('dealerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);try{enqueue({kind:'dealer',name:f.get('name'),phone:f.get('phone'),city:f.get('city')});$('dealer').close();}catch(e){alert(e.message);}};
$('newDealer').onclick=()=>{$('dealerForm').reset();$('dealer').showModal();};$('cancelDealer').onclick=()=>$('dealer').close();$('cancelPayment').onclick=()=>$('payment').close();$('search').oninput=draw;$('tabDealers').onclick=()=>{$('dealersView').hidden=false;$('historyView').hidden=true;};$('tabHistory').onclick=()=>history();$('retry').onclick=flush;$('refresh').onclick=async()=>{if(await refresh())await flush();};$('logout').onclick=async()=>{try{await api('logout',{});loggedIn=false;data={dealers:[],ops:[]};$('cabinet').hidden=true;$('login').hidden=false;status(queue.length?'Вы вышли. На телефоне остались неотправленные записи.':'Вы вышли из кабинета');}catch(e){status(e.message);}};
addEventListener('online',flush);addEventListener('offline',()=>status('Нет связи. Новые записи будут ожидать отправки на телефоне.'));
setInterval(()=>{if(loggedIn&&!document.hidden&&!$('payment').open&&!$('dealer').open&&!flushing)void refresh();},30000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('/mobile/sw.js').catch(()=>{});
void refresh().then(ok=>{if(ok)void flush();});
