'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(require.resolve('../../app/index.html'),'utf8');
const source=html.slice(html.indexOf('// Payment identity belongs'),html.indexOf('\nlet saleDealerCursor='));
function harness(){
 const node=()=>{const classes=new Set();return {value:'',innerHTML:'',disabled:false,focus(){},classList:{toggle:(c,on)=>on?classes.add(c):classes.delete(c),contains:c=>classes.has(c)}}};
 const nodes=Object.fromEntries(['paymentChooser','paymentSelected','paymentForm','paymentSave','payAmount','payMethod','payNote','paymentDealerSearch'].map(id=>[id,node()]));
 let seq=100,saves=0;const alerts=[],reports=[];
 const ctx={...nodes,window:null,state:{dealers:[{id:1,name:'Первый дилер',phone:'111'},{id:2,name:'Второй дилер',phone:'222'}],ops:[{id:11,type:'sale',dealerId:1,total:100},{id:12,type:'sale',dealerId:2,total:200}]},esc:s=>String(s),money:n=>String(n),setTimeout:f=>f(),alert:s=>alerts.push(s),confirm:()=>true,nextEntityId:()=>++seq,debtOf:id=>ctx.state.ops.filter(o=>String(o.dealerId)===String(id)).reduce((sum,o)=>sum+(o.type==='payment'?-o.total:o.total),0),render(){ctx.renderPaymentSelection()},save(){saves++;ctx.render()},showDebtReport:(...args)=>reports.push(args),closeDealerModal(){},go(){ctx.render()}};
 ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);ctx.render();
 return {ctx,nodes,alerts,reports,saves:()=>saves,id:()=>vm.runInContext('selectedPayDealerId',ctx),fill:(amount=25)=>{ctx.payAmount.value=String(amount);ctx.payMethod.value='Перевод';ctx.payNote.value=' примечание ';},payments:()=>ctx.state.ops.filter(o=>o.type==='payment')};
}
test('payment form contains only the method dropdown; no dealer control is regenerated by render',()=>{
 const form=html.slice(html.indexOf('<div id="paymentForm"'),html.indexOf('</section>',html.indexOf('<div id="paymentForm"')));
 assert.equal((form.match(/<select /g)||[]).length,1);assert.match(form,/id="payMethod"/);assert.doesNotMatch(html,/payDealer/);
});
test('selected ID and draft survive render, save, reordered synced dealers and fresh dealer objects; save targets that ID',()=>{
 const h=harness();h.ctx.selectPayDealer(2);h.fill();
 for(let i=0;i<10;i++){h.ctx.state=JSON.parse(JSON.stringify(h.ctx.state));h.ctx.state.dealers.reverse();h.ctx.render();h.ctx.save();}
 h.ctx.state.dealers.find(d=>d.id===2).name='Второй дилер обновлён';h.ctx.render();assert.match(h.ctx.paymentSelected.innerHTML,/Второй дилер обновлён/);assert.match(h.ctx.paymentSelected.innerHTML,/200/);
 assert.equal(h.id(),2);assert.equal(h.ctx.payAmount.value,'25');assert.equal(h.ctx.payMethod.value,'Перевод');assert.equal(h.ctx.payNote.value,' примечание ');assert.equal(h.ctx.paymentChooser.classList.contains('hidden'),true);
 h.ctx.makePayment();assert.equal(h.payments().length,1);const op=h.payments()[0];assert.equal(op.dealerId,2);assert.equal(op.total,25);assert.equal(op.method,'Перевод');assert.equal(op.note,'примечание');assert.equal(op.beforeDebt,200);assert.equal(op.afterDebt,175);assert.equal(h.ctx.debtOf(1),100);assert.equal(h.id(),2);assert.equal(h.ctx.paymentForm.classList.contains('hidden'),false);assert.match(h.ctx.paymentSelected.innerHTML,/175/);assert.equal(h.reports[0][0],2);
 h.ctx.makePayment();assert.equal(h.payments().length,1);
});
test('missing selected dealer never falls back to another; preserve identity and draft but block save',()=>{
 const h=harness();h.ctx.selectPayDealer(2);h.fill();h.ctx.state.dealers=h.ctx.state.dealers.filter(d=>d.id!==2);h.ctx.render();assert.equal(h.id(),2);assert.equal(h.ctx.paymentSave.disabled,true);assert.match(h.ctx.paymentSelected.innerHTML,/Второй дилер/);h.ctx.makePayment();assert.equal(h.payments().length,0);assert.equal(h.ctx.payAmount.value,'25');assert.match(h.alerts[0],/больше недоступен/);
});
test('explicit Back and selecting a different dealer clears the old payment draft; same dealer does not',()=>{
 const h=harness();h.ctx.openPaymentForDealer(1);h.fill();h.ctx.selectPayDealer(1);assert.equal(h.ctx.payAmount.value,'25');h.ctx.selectPayDealer(999);assert.equal(h.id(),1);assert.equal(h.ctx.payAmount.value,'25');h.ctx.openPaymentForDealer(2);assert.equal(h.id(),2);assert.equal(h.ctx.payAmount.value,'');assert.equal(h.ctx.payMethod.value,'');assert.equal(h.ctx.payNote.value,'');h.fill();h.ctx.clearPayDealer();assert.equal(h.id(),null);assert.equal(h.ctx.paymentChooser.classList.contains('hidden'),false);h.ctx.makePayment();assert.equal(h.payments().length,0);h.ctx.selectPayDealer(1);assert.equal(h.ctx.payAmount.value,'');
});
test('cancelled overpayment and invalid amount preserve selection and create no payment',()=>{
 const h=harness();h.ctx.selectPayDealer(1);h.fill(150);h.ctx.confirm=()=>false;h.ctx.makePayment();assert.equal(h.id(),1);assert.equal(h.ctx.payAmount.value,'150');assert.equal(h.payments().length,0);h.ctx.payAmount.value='Infinity';h.ctx.makePayment();assert.equal(h.payments().length,0);
});
test('dealer changed or removed during confirmation cannot receive the previous draft',()=>{
 for(const action of ['change','remove']){const h=harness();h.ctx.selectPayDealer(1);h.fill(150);h.ctx.confirm=()=>{if(action==='change')h.ctx.selectPayDealer(2);else h.ctx.state.dealers=h.ctx.state.dealers.filter(d=>d.id!==1);return true};h.ctx.makePayment();assert.equal(h.payments().length,0);assert.match(h.alerts[0],/изменился или больше недоступен/);}
});
