'use strict';
const {app,ipcMain,safeStorage}=require('electron');
const fs=require('fs'),path=require('path');
const {fileURLToPath}=require('url');
const pending=new Map();
const configPath=()=>path.join(app.getPath('userData'),'assistant-audio.json');
function read(){try{return JSON.parse(fs.readFileSync(configPath(),'utf8'))}catch{return {}}}
function publicConfig(){const c=read();return {mode:c.mode==='cloud'?'cloud':'windows',hasKey:!!c.key}}
function trusted(e){try{return e.senderFrame===e.sender.mainFrame&&fileURLToPath(e.senderFrame.url)===path.join(__dirname,'index.html')}catch{return false}}
function register(name,fn){ipcMain.handle('audio:'+name,async(e,...args)=>{if(!trusted(e))return {ok:false,message:'Недопустимый источник запроса.'};try{return await fn(e,...args)}catch{return {ok:false,message:'Не удалось выполнить запрос. Проверь подключение и настройки помощника.'}}})}
function cancel(e){for(const [id,item] of pending){if(item.owner===e.sender.id){item.controller.abort();pending.delete(id)}}return {ok:true}}
register('config',()=>({ok:true,...publicConfig()}));
register('save',(_e,v)=>{if(!v||!['windows','cloud'].includes(v.mode))return {ok:false,message:'Выбери режим речи.'};const c=read();if(v.clearKey)delete c.key;if(v.key){if(typeof v.key!=='string'||v.key.length>512||/[\r\n]/.test(v.key))return {ok:false,message:'Некорректный ключ.'};if(!safeStorage.isEncryptionAvailable())return {ok:false,message:'Windows не может безопасно сохранить ключ.'};c.key=safeStorage.encryptString(v.key.trim()).toString('base64')}if(v.mode==='cloud'&&!c.key)return {ok:false,message:'Для облачной речи нужен API-ключ.'};c.mode=v.mode;fs.writeFileSync(configPath(),JSON.stringify(c),{mode:0o600});return {ok:true,...publicConfig()}});
register('cancel',cancel);
async function request(e,kind,body,headers={}){const c=read();if(c.mode!=='cloud'||!c.key)return {ok:false,message:'Подключи облачную речь в настройках ИИ-помощника.'};const key=safeStorage.decryptString(Buffer.from(c.key,'base64'));const controller=new AbortController();const id=Symbol();pending.set(id,{owner:e.sender.id,controller});const timer=setTimeout(()=>controller.abort(),45000);try{const r=await fetch('https://api.openai.com/v1/audio/'+kind,{method:'POST',headers:{Authorization:'Bearer '+key,...headers},body,signal:controller.signal,redirect:'error'});if(!r.ok)return {ok:false,message:r.status===401?'Сервис отклонил ключ. Проверь API-ключ.':r.status===429?'Лимит речевого сервиса исчерпан. Проверь баланс и лимиты.':r.status===403?'Речевой сервис недоступен для этого подключения.':'Ошибка речевого сервиса: '+r.status};if(kind==='speech')return {ok:true,audio:Buffer.from(await r.arrayBuffer()).toString('base64')};const data=await r.json();return {ok:true,text:String(data.text||'').trim()}}catch(err){return {ok:false,message:controller.signal.aborted?'Запрос остановлен или истекло время ожидания.':'Нет соединения с речевым сервисом.'}}finally{clearTimeout(timer);pending.delete(id)}}
register('transcribe',(e,v)=>{if(!v||!(v.bytes instanceof Uint8Array)||v.bytes.length<100||v.bytes.length>4*1024*1024)return {ok:false,message:'Некорректная или слишком большая запись.'};const form=new FormData();form.append('model','gpt-4o-mini-transcribe');form.append('language','ru');form.append('file',new Blob([v.bytes],{type:'audio/webm'}),'request.webm');return request(e,'transcriptions',form)});
register('speak',(e,text)=>{if(typeof text!=='string'||!text.trim()||text.length>3000)return {ok:false,message:'Ответ слишком длинный для озвучки.'};return request(e,'speech',JSON.stringify({model:'gpt-4o-mini-tts',voice:'coral',input:text,response_format:'mp3',instructions:'Speak in natural conversational Russian, warmly and clearly, at a normal pace. Avoid a robotic or announcer tone.'}),{'Content-Type':'application/json'})});
app.on('web-contents-created',(_e,wc)=>{wc.on('destroyed',()=>cancel({sender:wc}));wc.session.setPermissionCheckHandler((contents,permission,_origin,details)=>{try{return permission==='media'&&details.mediaType==='audio'&&fileURLToPath(contents.getURL())===path.join(__dirname,'index.html')}catch{return false}});wc.session.setPermissionRequestHandler((contents,permission,callback,details)=>{let allow=false;try{allow=permission==='media'&&details.mediaTypes?.length===1&&details.mediaTypes[0]==='audio'&&fileURLToPath(contents.getURL())===path.join(__dirname,'index.html')}catch{}callback(allow)})});
app.on('before-quit',()=>{for(const item of pending.values())item.controller.abort()});
