(()=>{
  'use strict';
  const api=window.audioAPI;if(!api)return;
  const $=id=>document.getElementById(id);
  const status=$('aiStatus'),transcript=$('voiceTranscript'),listen=$('aiListen');
  if(!listen)return;
  let generation=0,stream=null,recorder=null,timer=null,meterTimer=null,context=null,player=null,playerUrl=null;
  let device='';try{device=localStorage.getItem('assistantMicrophone')||''}catch{}
  const sayStatus=t=>{status.textContent=t};
  function release(){clearTimeout(timer);clearInterval(meterTimer);timer=meterTimer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(context){context.close().catch(()=>{});context=null}$('audioLevel').value=0;listen.classList.remove('listening');$('voiceAssistantBtn').classList.remove('listening')}
  function stop(){generation++;if(recorder){recorder.onstop=null;try{if(recorder.state!=='inactive')recorder.stop()}catch{}recorder=null}release();if(player){player.pause();player=null}if(playerUrl){URL.revokeObjectURL(playerUrl);playerUrl=null}window.speechSynthesis?.cancel();api.cancel().catch(()=>{});window.voiceAPI?.stop().catch(()=>{});listen.disabled=false;$('audioFinish').disabled=true;sayStatus('Микрофон выключен.')}
  async function play(blob,id){if(id!==generation)return;playerUrl=URL.createObjectURL(blob);const audio=new Audio(playerUrl);player=audio;audio.onended=()=>{if(id===generation){URL.revokeObjectURL(playerUrl);playerUrl=null;player=null}};await audio.play()}
  async function speak(text){stop();const id=generation;try{const c=await api.config();if(id!==generation)return;if(c.mode!=='cloud'){const voices=window.speechSynthesis?.getVoices()||[];const ru=voices.filter(v=>/^ru[-_]/i.test(v.lang));let selected='';try{selected=localStorage.getItem('uchetVoiceSelected8917')||''}catch{}const voice=ru.find(v=>v.name===selected)||ru[0];if(!voice){sayStatus('Нет русского системного голоса. Подключи облачную речь в настройках.');return}const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.lang='ru-RU';u.rate=1;window.speechSynthesis.speak(u);return}sayStatus('Готовлю голосовой ответ…');const r=await api.speak(text);if(id!==generation)return;if(!r.ok){sayStatus(r.message);return}const bytes=Uint8Array.from(atob(r.audio),c=>c.charCodeAt(0));await play(new Blob([bytes],{type:'audio/mpeg'}),id);sayStatus('Ответ озвучивается. Микрофон выключен.')}catch{if(id===generation)sayStatus('Не удалось воспроизвести голос. Ответ доступен текстом.')}}
  window.assistantAudio={stop,speak};
  const meter=document.createElement('div');meter.innerHTML='<label>Уровень микрофона <meter id="audioLevel" min="0" max="1" value="0" style="width:180px"></meter></label> <button id="audioFinish" type="button" class="secondary" disabled>Готово — распознать</button>';listen.parentElement.after(meter);
  $('audioFinish').onclick=()=>{if(recorder?.state==='recording')recorder.stop()};
  async function devices(){const list=await navigator.mediaDevices.enumerateDevices();const select=$('audioDevice');select.replaceChildren(new Option('Микрофон Windows по умолчанию',''));list.filter(d=>d.kind==='audioinput').forEach((d,i)=>select.add(new Option(d.label||'Микрофон '+(i+1),d.deviceId)));select.value=[...select.options].some(o=>o.value===device)?device:'';device=select.value}
  async function capture(test){stop();const id=generation;listen.disabled=true;try{const config=await api.config();if(id!==generation)return;if(!test&&config.mode!=='cloud'){sayStatus('Запускаю распознавание Windows…');const r=await window.voiceAPI.listenOnce();if(id!==generation)return;listen.disabled=false;if(!r.ok){transcript.textContent=r.message;sayStatus('Микрофон выключен.');return}submit(r.text);return}
    sayStatus('Открываю микрофон…');const opened=await navigator.mediaDevices.getUserMedia({audio:{...(device?{deviceId:{exact:device}}:{}),echoCancellation:true,noiseSuppression:true},video:false});if(id!==generation){opened.getTracks().forEach(t=>t.stop());return}stream=opened;
    await devices();if(id!==generation)return;
    const chunks=[];let peak=0,speechAt=0,lastVoice=performance.now();const started=performance.now();
    context=new AudioContext();await context.resume();if(id!==generation)return;const analyser=context.createAnalyser();analyser.fftSize=1024;context.createMediaStreamSource(stream).connect(analyser);const samples=new Float32Array(analyser.fftSize);
    recorder=new MediaRecorder(stream,{mimeType:'audio/webm;codecs=opus'});const recording=recorder;
    recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
    recording.onerror=()=>{if(id===generation){stop();sayStatus('Не удалось записать звук. Проверь выбранный микрофон.')}};
    recording.onstop=async()=>{if(id!==generation)return;recorder=null;release();$('audioFinish').disabled=true;try{const blob=new Blob(chunks,{type:'audio/webm'});if(peak<.008){sayStatus('Звук не обнаружен. Выбери другой микрофон или проверь его подключение.');return}if(test){sayStatus('Проверка: воспроизвожу запись. Микрофон выключен.');await play(blob,id);return}sayStatus('Микрофон выключен. Распознаю…');const bytes=new Uint8Array(await blob.arrayBuffer());if(id!==generation)return;const r=await api.transcribe({bytes});if(id!==generation)return;if(!r.ok){sayStatus(r.message);return}if(!r.text){sayStatus('Речь не распознана. Повтори запрос.');return}submit(r.text)}catch{if(id===generation)sayStatus('Ошибка обработки записи. Повтори запрос.')}finally{if(id===generation)listen.disabled=false}};
    meterTimer=setInterval(()=>{if(id!==generation)return;analyser.getFloatTimeDomainData(samples);const rms=Math.sqrt(samples.reduce((n,v)=>n+v*v,0)/samples.length);peak=Math.max(peak,rms);$('audioLevel').value=Math.min(1,rms*8);const now=performance.now();if(rms>.02){speechAt=speechAt||now;lastVoice=now}if(!test&&speechAt&&now-lastVoice>1800&&now-started>2200&&recording.state==='recording')recording.stop()},100);
    recording.start();listen.classList.add('listening');$('voiceAssistantBtn').classList.add('listening');$('audioFinish').disabled=!!test;sayStatus(test?'Скажи несколько слов. Проверка записи — 4 секунды.':'Слушаю. Скажи запрос, затем сделай паузу или нажми «Готово».');timer=setTimeout(()=>{if(id===generation&&recording.state==='recording')recording.stop()},test?4000:15000);
  }catch(e){if(id===generation){stop();const errors={NotAllowedError:'Доступ к микрофону запрещён. Разреши доступ для классических приложений в настройках Windows.',NotFoundError:'Микрофон не найден. Подключи его и повтори.',NotReadableError:'Микрофон занят или недоступен. Закрой другую запись и повтори.',OverconstrainedError:'Выбранный микрофон отключён. Выбери другой в настройках помощника.'};sayStatus(errors[e.name]||'Не удалось включить микрофон. Проверь подключение.')}}}
  function submit(text){transcript.textContent='Вы сказали: '+text;$('aiText').value=text;$('aiRun').click()}
  listen.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();capture(false)},true);
  $('aiStop').addEventListener('click',stop,true);$('aiClose').addEventListener('click',stop,true);
  $('voiceAssistantModal').addEventListener('click',e=>{if(e.target===$('voiceAssistantModal'))stop()},true);window.addEventListener('beforeunload',stop);
  const settings=$('assistantSettings');if(settings){const card=document.createElement('div');card.className='card';card.innerHTML=`<h3>Микрофон и естественная речь</h3><label>Микрофон<select id="audioDevice"><option value="">Микрофон Windows по умолчанию</option></select></label><button type="button" id="audioTest" class="secondary">Проверить микрофон</button><p>Проверка записывает 4 секунды и воспроизводит их на этом компьютере. Запись не отправляется в интернет.</p><label>Режим<select id="audioMode"><option value="windows">Системная речь Windows</option><option value="cloud">Облачная речь OpenAI — естественный голос</option></select></label><p>Облачный режим отправляет запись запроса и текст озвучиваемого ответа в OpenAI. Нужны интернет, API-ключ и оплаченный доступ к API. Голос создаётся искусственным интеллектом.</p><label>API-ключ<input id="audioKey" type="password" autocomplete="off" placeholder="Введи ключ здесь, не в чате"></label><div class="aiActions"><button type="button" id="audioSave" class="primary">Сохранить подключение</button><button type="button" id="audioForget" class="secondary">Удалить ключ</button></div><p id="audioConfigStatus"></p>`;settings.appendChild(card);
    $('audioDevice').onchange=()=>{stop();device=$('audioDevice').value;localStorage.setItem('assistantMicrophone',device)};
    $('audioTest').onclick=()=>{$('voiceAssistantModal').classList.remove('hidden');capture(true)};
    const refresh=async()=>{const c=await api.config();$('audioMode').value=c.mode||'windows';$('audioConfigStatus').textContent=c.hasKey?'Ключ сохранён на этом компьютере.':'Облачная речь пока не подключена.'};
    $('audioSave').onclick=async()=>{stop();const r=await api.save({mode:$('audioMode').value,key:$('audioKey').value});if(r.ok){$('audioKey').value='';await refresh()}else $('audioConfigStatus').textContent=r.message};
    $('audioForget').onclick=async()=>{stop();const r=await api.save({mode:'windows',clearKey:true});if(r.ok){$('audioKey').value='';await refresh()}else $('audioConfigStatus').textContent=r.message};
    refresh().catch(()=>{});devices().catch(()=>{});
  }
  document.documentElement.dataset.uchetRuntime='8.9.27';
})();
