(()=>{
 let opId=null,selected=null,previousFocus=null,busy=false;
 const box=document.createElement('div');box.id='receiptAddModal';box.className='hidden';box.style.cssText='position:fixed;inset:0;z-index:650;background:#0008;display:flex;align-items:center;justify-content:center;padding:20px';
 box.innerHTML=`<div class="card" role="dialog" aria-modal="true" aria-labelledby="receiptAddTitle" style="width:min(740px,95vw);max-height:90vh;overflow:auto"><h2 id="receiptAddTitle"></h2><p id="receiptAddDealer"></p><label>Поиск товара<input id="receiptAddSearch" class="search" placeholder="Название или артикул" autocomplete="off"></label><div id="receiptAddList" style="max-height:230px;overflow:auto;margin:10px 0"></div><p id="receiptAddSelected">Выбери товар</p><div class="form"><label>Цена<select id="receiptAddPriceType"><option value="retail">Розница</option><option value="wholesale">Опт</option></select></label><label>Количество<input id="receiptAddQty" type="number" min="0.001" step="any" value="1"></label><label>Цена за единицу<input id="receiptAddPrice" type="number" min="0" step="0.01"></label></div><p id="receiptAddTotal"></p><p id="receiptAddError" role="alert" style="color:#a22"></p><div class="actions"><button id="receiptAddCommit" type="button" class="primary">Добавить в накладную</button><button id="receiptAddCancel" type="button" class="secondary">Отмена</button></div></div>`;
 document.body.appendChild(box);const $=id=>document.getElementById(id);const norm=v=>String(v||'').toLowerCase().replace(/ё/g,'е');
 const error=t=>$('receiptAddError').textContent=t;
 const price=()=>{const p=state.products.find(p=>p.id===selected);if(p)$('receiptAddPrice').value=($('receiptAddPriceType').value==='wholesale'?+p.wholesalePrice||0:+p.retailPrice||0);total()};
 function total(){const v=Number($('receiptAddQty').value)*Number($('receiptAddPrice').value);$('receiptAddTotal').textContent=Number.isFinite(v)?'Добавится к сумме накладной и долгу: '+money(v):''}
 function list(){const q=norm($('receiptAddSearch').value);const matches=state.products.filter(p=>!p.archived&&norm(p.name+' '+(p.article||'')).includes(q)).slice(0,100);$('receiptAddList').replaceChildren();for(const p of matches){const b=document.createElement('button');b.type='button';b.className='secondary';b.style.cssText='display:block;width:100%;text-align:left;margin:4px 0';b.textContent=(p.article?p.article+' · ':'')+p.name;b.onclick=()=>{selected=p.id;$('receiptAddSelected').textContent=p.name+' · '+(p.unit||'шт');price();$('receiptAddQty').focus();$('receiptAddQty').select()};$('receiptAddList').appendChild(b)}}
 function close(){box.classList.add('hidden');opId=null;selected=null;if(previousFocus?.isConnected)previousFocus.focus()}
 window.openReceiptAdd=id=>{const op=state.ops.find(o=>String(o.id)===String(id)&&o.type==='sale');if(!op)return;previousFocus=document.activeElement;opId=op.id;selected=null;$('receiptAddTitle').textContent='Добавить товар в накладную № '+op.receiptNo;$('receiptAddDealer').textContent='Покупатель: '+(state.dealers.find(d=>d.id===op.dealerId)?.name||op.dealer);$('receiptAddSearch').value='';$('receiptAddQty').value='1';$('receiptAddPrice').value='';$('receiptAddSelected').textContent='Выбери товар';error('');total();list();box.classList.remove('hidden');$('receiptAddSearch').focus()};
 $('receiptAddSearch').oninput=list;$('receiptAddSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('receiptAddList').querySelector('button')?.click()}};
 $('receiptAddPriceType').onchange=price;$('receiptAddQty').oninput=total;$('receiptAddPrice').oninput=total;$('receiptAddCancel').onclick=close;box.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}});
 $('receiptAddCommit').onclick=()=>{if(busy)return;busy=true;$('receiptAddCommit').disabled=true;try{if(selected===null)throw Error('Выбери товар.');if(!$('receiptAddPrice').value.trim())throw Error('Укажи цену.');const qty=Number($('receiptAddQty').value),value=Number($('receiptAddPrice').value);const p=state.products.find(p=>p.id===selected);if(p&&qty>(+p.stock||0)&&!confirm('Товара недостаточно на складе. Добавить его с отрицательным остатком?'))return;
 const result=window.receiptAddCore.append(state,opId,selected,qty,value);const id=opId;
 // Persist the operation and stock change together before updating the visible state.
 localStorage.setItem(KEY,JSON.stringify(result.state));state=result.state;close();
 try{render();refreshReceiptViews(id)}catch(e){console.error('Обновление вида накладной',e)}
 if(!syncApplying&&state.sync?.enabled){clearTimeout(syncSaveTimer);syncSaveTimer=setTimeout(()=>syncPush(false),350)}
 }catch(e){error(e.message||'Не удалось сохранить товар.')}finally{busy=false;$('receiptAddCommit').disabled=false}};
})();
