process.chdir(require('node:path').resolve(__dirname,'../..'));
const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {EventEmitter}=require('node:events');
test('Windows recognition stops its child and permits a fresh request',async()=>{const handlers={},children=[];const spawn=()=>{const p=new EventEmitter();p.stdout=new EventEmitter();p.stderr=new EventEmitter();p.kill=()=>{p.killed=true};children.push(p);return p};const electron={app:{on(){}},ipcMain:{handle:(n,fn)=>handlers[n]=fn}};vm.runInNewContext(fs.readFileSync('app/main-8922.js','utf8'),{require:n=>n==='electron'?electron:n==='child_process'?{spawn}:{},process:{platform:'win32'},setTimeout,clearTimeout});const pending=handlers['assistant:listenWindows']();handlers['assistant:stopWindows']();assert.equal(children[0].killed,true);assert.equal((await pending).ok,false);const next=handlers['assistant:listenWindows']();children[1].stdout.emit('data',Buffer.from('Цена плёнки'));children[1].emit('exit',0);assert.deepEqual(JSON.parse(JSON.stringify(await next)),{ok:true,text:'Цена плёнки'});});
test('Missing Russian engine produces actionable error',async()=>{const handlers={};let child;vm.runInNewContext(fs.readFileSync('app/main-8922.js','utf8'),{require:n=>n==='electron'?{app:{on(){}},ipcMain:{handle:(n,f)=>handlers[n]=f}}:n==='child_process'?{spawn:()=>{child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>{};return child}}:{},process:{platform:'win32'},setTimeout,clearTimeout});const p=handlers['assistant:listenWindows']();child.emit('exit',4);assert.match((await p).message,/нет совместимого русского/)});
test('Audio bridge rejects remote sender, encrypts key, constructs API calls and cancels',async()=>{const handlers={},listeners={};let stored='{}',requests=[];const e={sender:{id:1},senderFrame:{url:require('node:url').pathToFileURL(require('node:path').resolve('app/index.html')).href}};e.sender.mainFrame=e.senderFrame;
const electron={app:{getPath:()=>'/data',on:(n,f)=>listeners[n]=f},ipcMain:{handle:(n,f)=>handlers[n]=f},safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from('encrypted:'+s),decryptString:b=>b.toString().replace('encrypted:','')}};
const fetch=async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>({text:'Цена плёнки'}),arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}};
vm.runInNewContext(fs.readFileSync('app/audio-service.js','utf8'),{require:n=>n==='electron'?electron:n==='fs'?{readFileSync:()=>stored,writeFileSync:(_p,v)=>stored=v}:require(n),__dirname:require('node:path').resolve('app'),Buffer,Uint8Array,Blob,FormData,AbortController,fetch,setTimeout,clearTimeout});
assert.equal((await handlers['audio:config']({...e,senderFrame:{url:'https://bad.invalid'}})).ok,false);
assert.equal((await handlers['audio:save'](e,{mode:'cloud',key:'test-key'})).ok,true);assert.ok(!stored.includes('test-key'));assert.equal((await handlers['audio:config'](e)).key,undefined);
assert.equal((await handlers['audio:transcribe'](e,{bytes:new Uint8Array(200)})).text,'Цена плёнки');assert.equal(requests[0].options.body.get('language'),'ru');assert.equal(requests[0].options.headers.Authorization,'Bearer test-key');
assert.equal((await handlers['audio:speak'](e,'Здравствуйте')).ok,true);assert.equal(JSON.parse(requests[1].options.body).model,'gpt-4o-mini-tts');assert.equal((await handlers['audio:transcribe'](e,{bytes:new Uint8Array(1)})).ok,false);
await handlers['audio:save'](e,{mode:'windows',clearKey:true});assert.equal((await handlers['audio:config'](e)).hasKey,false);assert.equal((await handlers['audio:speak'](e,'Привет')).ok,false);
});
test('Russian price and deletion patterns match whole Cyrillic words',()=>{const source=fs.readFileSync('app/assistant-8921.js','utf8');const boundary='(?:(?<![а-яa-z0-9_])(?=[а-яa-z0-9_])|(?<=[а-яa-z0-9_])(?![а-яa-z0-9_]))';assert.ok(source.includes(boundary));const del=new RegExp(boundary+'(удали|удалить|сотри|стереть|очисти|очистить)'+boundary);assert.equal(del.test('удали дилера'),true);assert.equal(del.test('удалить чек'),true);assert.equal(del.test('цена удалина'),false);assert.equal(new RegExp(boundary+'цен').test('цена мат 303'),true)});
function uiHarness(){const elements=new Map();class El{constructor(){this.handlers={};this.classList={add(){},remove(){}};this.options=[];this.value='';this.parentElement=this}set innerHTML(v){for(const m of v.matchAll(/id="([^"]+)"/g))if(!elements.has(m[1]))elements.set(m[1],new El())}appendChild(){}after(){}replaceChildren(...v){this.options=v}add(v){this.options.push(v)}addEventListener(n,f){(this.handlers[n]??=[]).push(f)}click(){for(const fn of this.handlers.click||[])fn({preventDefault(){},stopImmediatePropagation(){}})} }
for(const id of ['aiStatus','voiceTranscript','aiListen','voiceAssistantBtn','aiStop','aiClose','aiText','aiRun','voiceAssistantModal','assistantSettings'])elements.set(id,new El());
let resolveMedia,transcriptions=0,stops=0,cancels=0;const media=new Promise(r=>resolveMedia=r);const win={addEventListener(){},speechSynthesis:{cancel(){},getVoices:()=>[]},voiceAPI:{stop:async()=>{},listenOnce:async()=>({ok:false,message:'missing'})},audioAPI:{config:async()=>({mode:'cloud'}),cancel:async()=>{cancels++},transcribe:async()=>{transcriptions++;return {ok:true,text:'x'}}}};const doc={getElementById:id=>elements.get(id),createElement:()=>new El(),documentElement:{dataset:{}}};
vm.runInNewContext(fs.readFileSync('app/audio-ui.js','utf8'),{window:win,document:doc,localStorage:{getItem:()=>'',setItem(){}},navigator:{mediaDevices:{enumerateDevices:async()=>[],getUserMedia:()=>media}},Option:class{constructor(t,v){this.value=v}},setTimeout,clearTimeout,setInterval,clearInterval,URL,Uint8Array,Blob,performance});
return {win,elements,resolveMedia:()=>resolveMedia({getTracks:()=>[{stop(){stops++}}]}),counts:()=>({transcriptions,stops,cancels})}}
test('Closing while microphone permission is pending releases late stream without upload',async()=>{const h=uiHarness();h.elements.get('aiListen').click();await new Promise(setImmediate);h.elements.get('aiClose').click();h.resolveMedia();await new Promise(setImmediate);assert.equal(h.counts().stops,1);assert.equal(h.counts().transcriptions,0);assert.equal(h.elements.get('aiListen').disabled,false)});
test('Microphone is never requested on assistant initialization',async()=>{const h=uiHarness();await new Promise(setImmediate);assert.deepEqual(h.counts(),{transcriptions:0,stops:0,cancels:0})});
