process.chdir(require('node:path').resolve(__dirname,'../..'));
const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {EventEmitter}=require('node:events');
function harness(){let resolve,reject,count=0;const handlers={},win=new EventEmitter();win.webContents=new EventEmitter();win.webContents.blur=()=>{};win.webContents.focus=()=>win.contentFocus++;win.webContents.send=()=>{};win.webContents.isFocused=()=>false;win.contentFocus=0;win.focus=()=>{};win.isFocused=()=>true;win.isDestroyed=()=>false;win.closes=0;win.close=()=>{let prevented=false;win.emit('close',{preventDefault(){prevented=true}});if(!prevented)win.closes++};const module={exports:{}};const electron={BrowserWindow:{fromWebContents:()=>win},ipcMain:{on:(n,f)=>handlers[n]=f},dialog:{showMessageBox:()=>{count++;return new Promise((a,b)=>{resolve=a;reject=b})},showMessageBoxSync:()=>0}};vm.runInNewContext(fs.readFileSync('app/window-safety.js','utf8'),{require:n=>n==='electron'?electron:require(n),module,__dirname:require('node:path').resolve('app'),setImmediate});module.exports.install(win);return {api:module.exports,win,handlers,count:()=>count,accept:()=>resolve({response:1}),cancel:()=>resolve({response:0}),fail:()=>reject(new Error('dialog failed'))}}
const tick=()=>new Promise(setImmediate);
test('Repeated close has one prompt; cancel keeps window alive; confirm closes once',async()=>{const h=harness();h.win.close();h.win.close();await tick();assert.equal(h.count(),1);assert.equal(h.win.closes,0);h.cancel();await tick();assert.equal(h.win.closes,0);h.win.close();await tick();assert.equal(h.count(),2);h.accept();await tick();assert.equal(h.win.closes,1)});
test('Dialog failure keeps app open and allows another attempt',async()=>{const h=harness();h.win.close();await tick();h.fail();await tick();assert.equal(h.win.closes,0);h.win.close();await tick();assert.equal(h.count(),2);h.cancel();await tick()});
test('An explicitly approved update bypasses the second close prompt',async()=>{const h=harness();const p=h.api.confirmExit(h.win);await tick();h.accept();assert.equal(await p,true);h.api.allowClose(h.win);h.win.close();assert.equal(h.win.closes,1);assert.equal(h.count(),1)});
test('Native dialog cancellation is false and an external sender cannot open it',()=>{const h=harness();const senderFrame={url:require('node:url').pathToFileURL(require('node:path').resolve('app/index.html')).href},e={senderFrame,sender:{mainFrame:senderFrame}};h.handlers['window:dialog'](e,{kind:'confirm',message:'Удалить?'});assert.equal(e.returnValue,false);const remote={senderFrame:{url:'https://example.com'},sender:{mainFrame:senderFrame}};h.handlers['window:dialog'](remote,{kind:'confirm'});assert.equal(remote.returnValue,false)});
test('Native content focus is recovered on a click',()=>{const h=harness();h.win.webContents.emit('before-mouse-event',{}, {type:'mouseDown'});assert.equal(h.win.contentFocus,1)});
function inputHarness(){const handlers={};let restore;const body={};const doc={getElementById:()=>null,body,activeElement:body,hasFocus:()=>true,documentElement:{dataset:{}},addEventListener:(n,f)=>handlers[n]=f};const win={windowAPI:{onRestoreInput:f=>restore=f,showDialog:()=>false}};vm.runInNewContext(fs.readFileSync('app/input-focus.js','utf8'),{window:win,document:doc});const field=()=>({isConnected:true,disabled:false,readOnly:false,matches:()=>true,getClientRects:()=>[{}],closest:()=>null,selectionStart:2,selectionEnd:4,selectionDirection:'forward',focus(){doc.activeElement=this},setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b},select(){this.selectionStart=0}});return {win,doc,field,handlers,restore:()=>restore()}}
test('Input recovery preserves selection and never steals another field or enables readonly',()=>{const h=inputHarness();const a=h.field(),b=h.field();h.handlers.focusin({target:a});h.restore();assert.equal(h.doc.activeElement,a);assert.equal(a.selectionStart,2);assert.equal(a.selectionEnd,4);h.doc.activeElement=b;h.restore();assert.equal(h.doc.activeElement,b);a.readOnly=true;h.win.forceInputFocus(a,true);assert.equal(a.readOnly,true);assert.equal(h.doc.activeElement,b);a.readOnly=false;a.disabled=true;h.win.forceInputFocus(a,true);assert.equal(a.disabled,true);assert.equal(h.doc.activeElement,b)});
