const {test}=require('node:test');const assert=require('node:assert/strict');const core=require('../../app/receipt-archive-core');
const clone=x=>JSON.parse(JSON.stringify(x));
function sample(){return {dealers:[{id:1},{id:2}],products:[{id:9,stock:8}],ops:[{id:20,type:'sale',dealerId:1,total:400,profit:100,items:[{productId:9,qty:2}]},{id:21,type:'payment',dealerId:1,total:100},{id:22,type:'sale',dealerId:2,total:500,items:[]}],receiptSeq:3}}
const debt=(s,id)=>s.ops.filter(o=>o.dealerId===id).reduce((sum,o)=>sum+(o.type==='payment'?-o.total:o.total),0);
function merge(a,b){const out=clone(b);out.ops=[...new Map([...a.ops,...b.ops].map(o=>[String(o.id),clone(o)])).values()];return core.merge(a,b,out)}
test('archive and restore preserve payments, other dealer, receipt identity and inventory exactly once',()=>{const before=sample(),s=core.transition(before,20,true,10);assert.equal(debt(s,1),-100);assert.equal(debt(s,2),500);assert.equal(s.products[0].stock,10);assert.equal(before.products[0].stock,8);assert.deepEqual(core.transition(s,20,true,20),s);const restored=core.transition(s,20,false,30);assert.equal(debt(restored,1),300);assert.equal(restored.products[0].stock,8);assert.deepEqual(restored.ops.find(o=>o.id===20),before.ops[0]);assert.equal(restored.receiptSeq,3);assert.deepEqual(core.transition(restored,20,false,40),restored)});
test('stale computer cannot resurrect receipt; repeated merges neither duplicate stock nor lose restoration',()=>{const old=sample(),deleted=core.transition(old,20,true,100);for(const s of [merge(old,deleted),merge(deleted,old)]){assert.equal(debt(s,1),-100);assert.equal(s.products[0].stock,10);assert.deepEqual(merge(deleted,s),s)}const restored=core.transition(deleted,20,false,50);for(const s of [merge(deleted,restored),merge(restored,deleted)]){assert.equal(debt(s,1),300);assert.equal(s.products[0].stock,8)}const deletedAgain=core.transition(restored,20,true,25);assert.equal(debt(merge(restored,deletedAgain),1),-100)});
test('simultaneous archive on two computers and unrelated stock edits converge',()=>{const a=core.transition(sample(),20,true,100),b=core.transition(sample(),20,true,101);assert.equal(merge(a,b).products[0].stock,10);b.products[0].stock=15;const restored=core.transition(a,20,false,200);assert.equal(merge(restored,b).products[0].stock,13)});
test('NewMatRos imported rows do not return inventory that was never deducted; appended goods do',()=>{const s=sample();s.ops[0].source='NewMatRos';s.ops[0].items=[{productId:9,qty:10,ceilingNo:1,article:'NM-MAT'},{productId:9,qty:2,stockTracked:true}];assert.equal(core.transition(s,20,true).products[0].stock,10)});
test('restoration refuses a removed dealer and a re-exported NewMatRos duplicate',()=>{let s=core.transition(sample(),20,true);s.dealers=[];assert.throws(()=>core.transition(s,20,false),/дилера/);s=sample();s.ops[0].source='NewMatRos';s.ops[0].newmatrosKeys=['ceiling'];s=core.transition(s,20,true);s.ops.push({id:24,type:'sale',source:'NewMatRos',newmatrosKey:'ceiling'});assert.throws(()=>core.transition(s,20,false),/повторно/)});

test('payment running balances reflect cancelled and restored sales',()=>{const s=core.transition(sample(),20,true);assert.equal(s.ops.find(o=>o.id===21).beforeDebt,0);assert.equal(s.ops.find(o=>o.id===21).afterDebt,-100);const restored=core.transition(s,20,false);assert.equal(restored.ops.find(o=>o.id===21).beforeDebt,400);assert.equal(restored.ops.find(o=>o.id===21).afterDebt,300)});
