'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../../app/sync-core-8962'),S=require('../../server/master-protocol-8962'),A=require('../../app/receipt-archive-core');
function fixture(){return {dealers:[{id:1,name:'Dealer'}],groups:[{id:1,name:'Group'}],products:[{id:1,name:'Product',stock:9,warehouseOpening:9,inventoryVersion:2,initialStock:9,retailPrice:200}],ops:[]}}
function harness(enabled=true){
 const nodes=new Map(),events=new Map(),storage=new Map([['db:warehouse-enabled',String(enabled)]]);
 function node(tag='div'){return {tag,children:[],style:{},dataset:{},classList:{add(){},remove(){}},value:'',checked:false,hidden:false,textContent:'',appendChild(n){this.children.push(n);n.parent=this;return n},append(...ns){ns.forEach(n=>this.appendChild(n))},setAttribute(){},closest(){return this},querySelector(){return null},querySelectorAll(){return []},focus(){},remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this)},get innerHTML(){return this._html||''},set innerHTML(s){this._html=s;for(const id of s.matchAll(/id="([^"]+)"/g))nodes.set(id[1],node())}}}
 for(const id of ['saleDealer','editProductId','editPinitialStock','pInitialStock','warehouseSave'])nodes.set(id,node());nodes.get('saleDealer').value='1';
 const main=node(),nav=node(),head=node(),body=node();
 const ctx={window:null,SyncCore8962:C,state:fixture(),KEY:'db',cart:[{productId:1,name:'Product',qty:10}],localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},document:{head,body,getElementById:id=>nodes.get(id)||null,createElement:node,querySelector:s=>s==='main'?main:s==='nav'?nav:null,addEventListener:(k,fn)=>events.set(k,fn),removeEventListener(){}},setTimeout:fn=>fn(),navigator:{clipboard:{writeText:async()=>{}}},render(){},editProduct(){},save(){ctx.warehouseStampSales?.();C.recalcInventory(ctx.state);ctx.render()},saveSale(){ctx.state.ops.push({id:Date.now(),type:'sale',dealerId:1,items:JSON.parse(JSON.stringify(ctx.cart)),total:2000});ctx.cart=[];ctx.save()},addEventListener(){},go(){}};
 ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../../app/final-interface.js'),'utf8'),ctx);
 return {ctx,nodes,storage,body,events,dialog:()=>body.children.find(n=>n.className==='negativeOverlay')?.children[0]};
}
test('9 available, selling 10 prompts; Cancel preserves sale and balance',()=>{const h=harness();h.ctx.saveSale();assert.equal(h.ctx.state.ops.length,0);assert.equal(h.ctx.state.products[0].stock,9);const d=h.dialog();assert.ok(d.children.some(n=>n.textContent.includes('в наличии 9, продажа 10')));d.children.at(-1).children[0].onclick();assert.equal(h.ctx.state.ops.length,0);assert.equal(h.dialog(),undefined)});
test('explicit confirmation sells in minus exactly once and records tracked sale',()=>{const h=harness();h.ctx.saveSale();h.ctx.saveSale();assert.equal(h.body.children.length,1);h.dialog().children.at(-1).children[1].onclick();assert.equal(h.ctx.state.ops.length,1);assert.equal(h.ctx.state.products[0].stock,-1);assert.equal(h.ctx.state.ops[0].inventoryTracked,true)});
test('disabled warehouse never blocks sale or alters balance, also after enabling/reloading',()=>{const h=harness(false);h.ctx.saveSale();assert.equal(h.dialog(),undefined);assert.equal(h.ctx.state.products[0].stock,9);assert.equal(h.ctx.state.ops[0].inventoryTracked,false);h.nodes.get('warehouseEnabled').checked=true;h.nodes.get('warehouseEnabled').onchange();assert.equal(h.ctx.state.products[0].stock,9);const restored=C.clone(h.ctx.state);C.enableInventory(restored);assert.equal(restored.products[0].stock,9);assert.equal(h.storage.get('db:warehouse-enabled'),'true')});
test('off sale deletion and restoration do not touch stock or old receipt prices',()=>{const s=fixture();s.ops=[{id:2,type:'sale',inventoryTracked:false,dealerId:1,items:[{productId:1,qty:10,price:180,total:1800}],total:1800}];const deleted=A.transition(s,2,true,1);C.recalcInventory(deleted);assert.equal(deleted.products[0].stock,9);const restored=A.transition(deleted,2,false,2);C.recalcInventory(restored);assert.equal(restored.products[0].stock,9);assert.equal(restored.ops[0].items[0].price,180)});
test('duplicate cart rows are summed for the shortage warning',()=>{const h=harness();h.ctx.cart=[{productId:1,qty:5},{productId:1,qty:5}];h.ctx.saveSale();assert.ok(h.dialog());assert.equal(h.ctx.state.ops.length,0)});
test('cart or stock changed while confirmation open requires fresh confirmation',()=>{const h=harness();h.ctx.saveSale();h.ctx.cart[0].qty=11;h.dialog().children.at(-1).children[1].onclick();assert.equal(h.ctx.state.ops.length,0);assert.ok(h.dialog().children.some(n=>n.textContent.includes('продажа 11')))});
test('expense, return and adjustment ledger recalculates and retries without duplication',()=>{const store={revision:1,state:fixture(),computers:{masterId:'master-device-123',devices:{}}};const device={id:'master-device-123',name:'Master'};const ops=[['expense','stock_expense',3],['return','stock_return',2],['adjust','stock_adjustment',-1]].map(([id,type,qty])=>({id,type,date:'2026-10-01',items:[{productId:1,qty,buyPrice:100}],total:0}));let next=S.update(store,{protocol:2,action:'changes',device,inventoryProtocol:2,changes:C.diffOps([],ops)});assert.equal(next.state.products[0].stock,7);next=S.update(next,{protocol:2,action:'changes',device,inventoryProtocol:2,changes:C.diffOps([],ops)});assert.equal(next.state.products[0].stock,7);assert.equal(next.state.ops.length,3)});
test('server rejects a second opening from an offline computer, but accepts retry of first',()=>{const store={revision:1,state:fixture(),computers:{masterId:'master-device-123',devices:{}}},device={id:'master-device-123',name:'Master'};const op={id:'opening-a',type:'stock_opening',date:'2026-10-01',items:[{productId:1,qty:0,buyPrice:0}],total:0};const body={protocol:2,action:'changes',device,inventoryProtocol:2,changes:C.diffOps([], [op])};const next=S.update(store,body);assert.equal(S.update(next,body).state.ops.length,1);assert.throws(()=>S.update(next,{...body,changes:C.diffOps([],[{...op,id:'opening-b',items:[{productId:1,qty:5,buyPrice:0}]}])}),/Начальный остаток уже введён/)});
test('off sale stays untracked through server roundtrip and stale computer retry',()=>{const store={revision:1,state:fixture(),computers:{masterId:'master-device-123',devices:{}}},device={id:'master-device-123',name:'Master'};const op={id:'off-sale',type:'sale',inventoryTracked:false,dealerId:1,total:1800,items:[{productId:1,qty:10,price:180}]};const body={protocol:2,action:'changes',device,inventoryProtocol:2,changes:C.diffOps([],[op])};const next=S.update(store,body);assert.equal(next.state.products[0].stock,9);assert.equal(S.update(next,body).state.products[0].stock,9);assert.equal(next.state.ops[0].items[0].price,180)});
test('first physical opening in a legacy database does not subtract historical sales twice',()=>{const s=fixture();delete s.products[0].inventoryVersion;delete s.products[0].warehouseOpening;s.ops=[{id:'old-sale',type:'sale',items:[{productId:1,qty:100,price:180}]}];C.enableInventory(s);assert.equal(s.products[0].stock,9);s.ops.push({id:'opening',type:'stock_opening',items:[{productId:1,qty:0,openingCount:9}]});C.recalcInventory(s);assert.equal(s.products[0].initialStock,9);assert.equal(s.products[0].stock,9);s.ops.push({id:'new-sale',type:'sale',inventoryTracked:true,items:[{productId:1,qty:2,price:200}]});C.recalcInventory(s);assert.equal(s.products[0].stock,7);assert.equal(s.ops[0].items[0].price,180)});
function contextRow(h,action){const row={dataset:{},getAttribute:()=>null,querySelectorAll:()=>[{getAttribute:()=>action}]};h.ctx.innerWidth=1280;h.ctx.innerHeight=900;h.events.get('contextmenu')({target:{closest:()=>row},clientX:200,clientY:200,preventDefault(){},stopImmediatePropagation(){}});return h.body.children.find(n=>n.className==='finalMenu')?.children.map(n=>n.textContent)}
test('sale context menu works with legacy renderer rows lacking data-op-id',()=>{const h=harness();h.ctx.state.ops.push({id:12,type:'sale',dealerId:1,items:[]});assert.deepEqual(contextRow(h,'showReceiptFromHistory(12)'),['Открыть','Изменить','Добавить товар','Внесено в журнал','Не внесено в журнал','Удалить'])});
test('payment context menu uses legacy debt-report operation ID, not dealer ID',()=>{const h=harness();h.ctx.state.ops.push({id:12,type:'payment',dealerId:1,total:100});assert.deepEqual(contextRow(h,'showDebtReport(1,12)'),['Изменить','Удалить'])});
test('deleted sale has no edit/delete menu',()=>{const h=harness();assert.equal(contextRow(h,'showReceiptFromHistory(12)'),undefined)});
